name: Python application

on:
  push:
    tags:
      - "v*"
    branches: [ "main" ]

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        
       #安装pip以及安装第三方库
      - name: Install dependencies
        run: |
          cd py_test 
          conda activate cinty
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. ./test.proto
        shell: cmd
          
       # 编译test.py
      - name: python running
        run: |
          cd py_test
          python3 main.py --line 2            
          python -m unittest  test_main.py 
          pyinstaller  -F main.py -n ${{ runner.os }}_test
     
          
       #上传文件
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} pyinstaller
          path: ./py_test/dist
          
      - name: download-artifact   
        uses: actions/download-artifact@v3
        with: 
          path: ./artifact
 
          
      - name: Create Release and Upload Release Asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: 'v0.0.1'
          automatic_release_tag: 'v0.0.1'
          files: ./artifact

            
