name: Python application

on:
  push:
    tags:
      - "v*"
    branches: [ "main" ]

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        
       #安装pip以及安装第三方库
      - name: Install dependencies
        run: |
          cd py_test 
          conda activate cinty
          python --version
        shell: cmd
          
 

            
