name: Python application

on:
  push:
    tags:
      - "v*"
    branches: [ "main" ]

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted]
      
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          cd py_test 
          C:\Users\Nooploop_test1\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe -F main.py
        shell: cmd
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} pyinstaller
          path: ./py_test/py_testdist
          
      - name: download-artifact   
        uses: actions/download-artifact@v3
        with: 
          path: ./artifact
 
          
      - name: Create Release and Upload Release Asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: 'v0.0.3'
          automatic_release_tag: 'v0.0.3'
          files: ./artifact
          
 

            
