
name: Python application

on:
  push:
    tags:
      - "v*"
    branches: [ "master" ]

#设置操作系统
jobs:
  build:
    strategy:
      matrix:
        os: [Windows,windows-latest]
      
    runs-on: ${{ matrix.os }} 

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-strict: false

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }} 
          path: .

          
          
 

            
